
/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
SELECT 
	country, 
	COUNT(customer_key) as customer_count 
FROM goldcustomers
GROUP BY country
ORDER BY customer_count DESC; 

-- Find total customers by gender
SELECT 
	gender, 
	COUNT(customer_key) as customer_count 
FROM goldcustomers
GROUP BY gender
ORDER BY customer_count DESC;

-- Find total products by category
SELECT 
	category, 
    COUNT(product_key) as product_count 
FROM goldproducts 
GROUP BY category
ORDER BY product_count DESC; 

-- What is the average costs in each category?
SELECT 
	category, 
    AVG(cost) as avg_cost
FROM goldproducts 
GROUP BY category 
ORDER BY avg_cost DESC;


-- What is the total revenue generated for each category?
SELECT 
	p.category, 
    SUM( s.sales_amount) total_revenue  
FROM goldproducts p 
LEFT JOIN goldsales s 
on p.product_key = s.product_key
GROUP BY p.category 
ORDER BY total_revenue DESC; 


-- What is the total revenue generated by each customer?
SELECT 
	s.customer_key,
    concat(c.first_name, ' ', c.last_name) as customer_name,
    SUM(s.sales_amount) as total_revenue 
FROM goldsales as s
LEFT JOIN goldcustomers as c
ON s.customer_key = c.customer_key
GROUP BY s.customer_key, customer_name 
ORDER BY total_revenue DESC;
    
    -- What is the distribution of sold items across countries?
SELECT 
	c.country, 
    SUM(s.quantity) as Quantity_sold
FROM goldcustomers as c
LEFT JOIN goldsales as s
ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY Quantity_sold DESC
